name: "Prerelease"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string


jobs:
  PreRelease:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{inputs.tag}}
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}

      - name: Build
        run: |
          pip install --upgrade hatch "click<8.3"
          hatch -v build

      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist
            dist_extras